services:
  protobuf-gen:
    build:
      context: .
      dockerfile: ./protobuf-gen/Dockerfile
    volumes:
      - ./protobuf-gen/generated/:/app/generated/

  svr:
    container_name: svr
    build:
      context: .
      dockerfile: ./svr/Dockerfile
    depends_on:
      - protobuf-gen
    volumes:
      - ./svr/pb:/app/generated


  web:
    container_name: web-wasm
    build:
      context: .
      dockerfile: ./web/Dockerfile
    depends_on:
      - protobuf-gen
    volumes:
      - ./web/proto:/app/proto
    ports:
      - "5001:8080"
