services:
  protobuf-gen-svr:
    build:
      context: .
      dockerfile: ./protobuf-gen/Dockerfile
    volumes:
      - ./svr/container/pb:/app/generated/pb
      - ./web/BlazorApp/proto:/app/pb

  svr:
    container_name: svr
    build:
      context: .
      dockerfile: ./svr/Dockerfile
    depends_on:
      - protobuf-gen-svr
    ports:
      - "50051:50051" # for internal grpc test
      - "8080:8080" # for grpc-web
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://svr:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 3

  web:
    container_name: web-wasm
    build:
      context: .
      dockerfile: ./web/Dockerfile
    depends_on:
      svr:
        condition: service_healthy
    volumes:
      - ./web/BlazorApp/proto:/app/BlazorApp/proto
    ports:
      - "5001:8080"
