services:
  protobuf-gen-svr:
    build:
      context: .
      dockerfile: ./protobuf-gen/Dockerfile
    volumes:
      - ./svr/container/pb:/app/generated/pb
      - ./web/BlazorApp/proto:/app/pb

  svr:
    container_name: svr
    build:
      context: .
      dockerfile: ./svr/Dockerfile
    depends_on:
      - protobuf-gen-svr



  web:
    container_name: web-wasm
    build:
      context: .
      dockerfile: ./web/Dockerfile
    depends_on:
      - svr
    volumes:
      - ./web/BlazorApp/proto:/app/BlazorApp/proto
    ports:
      - "5001:8080"
