services:
  protobuf-gen:
    build:
      context: .
      dockerfile: ./protobuf-gen/Dockerfile
    volumes:
      - ./protobuf-gen/generated/:/app/generated/

  web:
    container_name: web-wasm
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - protobuf-gen
    volumes:
      - ./protobuf-gen/generated:/app/generated
    ports:
      - "5001:8080"
