// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pb/greet/greet.proto

package greet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetRequest) Reset() {
	*x = GreetRequest{}
	mi := &file_pb_greet_greet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRequest) ProtoMessage() {}

func (x *GreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_greet_greet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRequest.ProtoReflect.Descriptor instead.
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return file_pb_greet_greet_proto_rawDescGZIP(), []int{0}
}

func (x *GreetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GreetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetReply) Reset() {
	*x = GreetReply{}
	mi := &file_pb_greet_greet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetReply) ProtoMessage() {}

func (x *GreetReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_greet_greet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetReply.ProtoReflect.Descriptor instead.
func (*GreetReply) Descriptor() ([]byte, []int) {
	return file_pb_greet_greet_proto_rawDescGZIP(), []int{1}
}

func (x *GreetReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pb_greet_greet_proto protoreflect.FileDescriptor

const file_pb_greet_greet_proto_rawDesc = "" +
	"\n" +
	"\x14pb/greet/greet.proto\x12\x05greet\"\"\n" +
	"\fGreetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"GreetReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2r\n" +
	"\aGreeter\x121\n" +
	"\x05Greet\x12\x13.greet.GreetRequest\x1a\x11.greet.GreetReply\"\x00\x124\n" +
	"\x06Greets\x12\x13.greet.GreetRequest\x1a\x11.greet.GreetReply\"\x000\x01BHZ,github.com/mzzz-zzm/blazor-scaffold/pb/greet\xaa\x02\x17BlazorGrpcWebApp.Sharedb\x06proto3"

var (
	file_pb_greet_greet_proto_rawDescOnce sync.Once
	file_pb_greet_greet_proto_rawDescData []byte
)

func file_pb_greet_greet_proto_rawDescGZIP() []byte {
	file_pb_greet_greet_proto_rawDescOnce.Do(func() {
		file_pb_greet_greet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_greet_greet_proto_rawDesc), len(file_pb_greet_greet_proto_rawDesc)))
	})
	return file_pb_greet_greet_proto_rawDescData
}

var file_pb_greet_greet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_greet_greet_proto_goTypes = []any{
	(*GreetRequest)(nil), // 0: greet.GreetRequest
	(*GreetReply)(nil),   // 1: greet.GreetReply
}
var file_pb_greet_greet_proto_depIdxs = []int32{
	0, // 0: greet.Greeter.Greet:input_type -> greet.GreetRequest
	0, // 1: greet.Greeter.Greets:input_type -> greet.GreetRequest
	1, // 2: greet.Greeter.Greet:output_type -> greet.GreetReply
	1, // 3: greet.Greeter.Greets:output_type -> greet.GreetReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_greet_greet_proto_init() }
func file_pb_greet_greet_proto_init() {
	if File_pb_greet_greet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_greet_greet_proto_rawDesc), len(file_pb_greet_greet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_greet_greet_proto_goTypes,
		DependencyIndexes: file_pb_greet_greet_proto_depIdxs,
		MessageInfos:      file_pb_greet_greet_proto_msgTypes,
	}.Build()
	File_pb_greet_greet_proto = out.File
	file_pb_greet_greet_proto_goTypes = nil
	file_pb_greet_greet_proto_depIdxs = nil
}
