FROM mcr.microsoft.com/devcontainers/dotnet:1-9.0-bookworm
# WORKDIR /devcontainers/blazor-scaffold
# RUN dotnet workload update

# COPY BlazorScaffold.sln ./
# COPY BlazorScaffold/BlazorScaffold.csproj ./BlazorScaffold/

# RUN dotnet restore
# COPY . ./
# RUN dotnet publish -c Release -o out
